name: Deploying Main Branch

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: [self-hosted,react-app-runner]

    env:
      PM2_PROCESS_NAME: react-app-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false
          
      - name: Install dependencies
        run: npm install 

      - name: Make Build
        run: npm run build

      - name: Start or Reload the Application
        run: |
          if pm2 list | grep -q "$PM2_PROCESS_NAME"; then
            echo "Process $PM2_PROCESS_NAME exists. Reloading..."
            pm2 reload "$PM2_PROCESS_NAME"
          else
            echo "Process $PM2_PROCESS_NAME does not exist. Starting..."
            pm2 start "npm start" --name "$PM2_PROCESS_NAME"
          fi
          pm2 save
      
        
      
